version: '3'
services:
    express:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_DSN=mongodb://host.docker.internal:27017/documents
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 1337:1337
        links:
            - mongodb
        command: "node app.js"

    express-production:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - NODE_ENV=production
        volumes:
            - ./:/app/
            - /app/node_modules/
        ports:
            - 1337:1337
        links:
            - mongodb
        command: "node app.js"

    mongodb:
        image: mongo
        environment:
            - MONGO_DATA_DIR=/data/db
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod